---
- name: Ensure jenkins directory on docker host
  file:
    state: directory
    mode: 0777
    path: /share/jenkins
  become: true

- name: Pull the latest official jenkins docker image
  docker_image:
    name: "jenkins/jenkins:lts"
  become: true

- name: Create a container from the jenkins docker image
  docker_container:
    name: "jenkins"
    image: "jenkins/jenkins:lts"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/share/jenkins:/var/jenkins_home"
    state: started
    restart_policy: unless-stopped
    recreate: no
  become: true
