---
- name: Set the package state based on how Ansible is installed.
  set_fact:
    ansible_package_state: "{{ 'present' if ansible_install_method == 'package' else 'absent' }}"

- name: Install Ansible.
  yum:
    name: ansible
    state: "{{ ansible_package_state }}"
    enablerepo: epel
  become: true

- name: Set up Ansible using Pip.
  include_tasks: setup-pip.yml
  when: ansible_install_method == 'pip'
