---

# NTP variables
ntp_daemon: ntpd
ntp_tzdata_package: tzdata
ntp_driftfile: /var/lib/ntp/drift
ntp_enabled: true
ntp_timezone: Etc/UTC
ntp_manage_config: true
ntp_servers:
  - "ntp1.aepsc.com"
ntp_restrict:
  - "127.0.0.1"
  - "::1"

