---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present
  become: true

- name: Ensure pip is current.
  pip:
    name: pip
    extra_args: --upgrade
    version: "{{ pip_version }}"
  become: true

- name: Install pip package dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_package_dependencies }}"
  become: true

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    extra_args: --upgrade
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  with_items: "{{ pip_install_packages }}"
  become: true
