---
# This playbook installs Jenkins in a container

- name: Installing Containerized Jenkins...
  hosts: jenkins

  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

    pip_package_dependencies:
      - python-devel

  roles:
#    - common
#    - repo-epel
#    - docker
    - pip
    - jenkinsc

  pre_tasks:

    - name: Install Artifactory repository entry
      template:
        src: ./files/artifactory.repo
        dest: /etc/yum.repos.d/artifactory.repo
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      tags: [repo, config]
      become: true
